### PR TITLE
Port code from prototype

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Includes:

* Hack scripts
* Copy pasted code from https://github.com/knative/eventing/pull/4849
* Vendored deps

Some unit tests are failing, but I'll tackle it in next PRs. This PR just initialize the code in the repo, starting from the prototype

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
I'm gonna work on fixing the tests in next prs

**Review by devguyio — APPROVED** [review]
/lgtm

**Review by devguyio — APPROVED** [review]
Approving again

**Pull request merged**
